{{- range $serviceName, $serviceConfig := .Values.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $serviceName }}-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---

{{- if $serviceConfig.pvc.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $serviceName }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}


{{- end }}

