{{- if .Values.serviceAccount.create -}}
{{- range $serviceName, $serviceConfig := .Values.modules }}
{{- if and (eq $serviceConfig.enabled true) ($serviceConfig.image.repository) }}

--- 

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-serviceaccount
  labels:
    {{- include "flask-kafka-apps.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

{{- end }}
{{- end }}
