apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
template:
  metadata:
    labels:
      app: app1
  spec:
    containers:
    - name: app1
      image: your-registry/app1:latest
    ports:
    - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
template:
  metadata:
    labels:
      app: app2
  spec:
    containers:
    - name: app2
      image: your-registry/app2:latest
    ports:
    - containerPort: 5000